/**
 * Generates governance policy YAML files compatible with
 * Microsoft Agent Governance Toolkit format.
 */

import type { GovernancePolicy, GovernanceCategory } from '../types/governance.js';
import { getByCategory, GOVERNANCE_CATEGORIES, GOVERNANCE_CATEGORY_LABELS } from './registry.js';
import type { RenderedFile } from '../types/template.js';

function severityToAction(severity: string): string {
  switch (severity) {
    case 'block': return 'deny';
    case 'warn': return 'audit';
    case 'info': return 'allow';
    default: return 'audit';
  }
}

function policyToYaml(policy: GovernancePolicy): string {
  const lines = [
    `  - name: "${policy.id}"`,
    `    display_name: "${policy.name}"`,
    `    description: "${policy.description}"`,
    `    category: "${policy.category}"`,
    `    severity: "${policy.severity}"`,
    `    action: "${severityToAction(policy.severity)}"`,
    `    weight: ${policy.weight}`,
  ];
  if (policy.fix) {
    lines.push(`    fix: "${policy.fix}"`);
  }
  if (policy.references && policy.references.length > 0) {
    lines.push(`    references:`);
    for (const ref of policy.references) {
      lines.push(`      - "${ref}"`);
    }
  }
  return lines.join('\n');
}

function generateCategoryYaml(category: GovernanceCategory): string {
  const policies = getByCategory(category);
  const label = GOVERNANCE_CATEGORY_LABELS[category];
  const lines = [
    `# ${label} Governance Policies`,
    `# Generated by vibe-init — compatible with Microsoft Agent Governance Toolkit`,
    `# https://github.com/microsoft/agent-governance-toolkit`,
    ``,
    `category: "${category}"`,
    `display_name: "${label}"`,
    `conflict_resolution: "deny_overrides"`,
    ``,
    `rules:`,
  ];
  for (const policy of policies) {
    lines.push(policyToYaml(policy));
    lines.push('');
  }
  lines.push(`defaults:`);
  lines.push(`  action: "allow"`);
  return lines.join('\n');
}

/**
 * Generate all governance policy YAML files.
 * Returns RenderedFile[] for writing via writeFileTree.
 */
export function generatePolicyYamlFiles(): RenderedFile[] {
  const files: RenderedFile[] = [];

  for (const category of GOVERNANCE_CATEGORIES) {
    const yaml = generateCategoryYaml(category);
    files.push({
      path: `.vibe/policies/${category}.yaml`,
      content: yaml,
    });
  }

  // Generate an index file
  const indexLines = [
    `# Governance Policy Index`,
    `# Generated by vibe-init`,
    `# Compatible with Microsoft Agent Governance Toolkit`,
    `# https://github.com/microsoft/agent-governance-toolkit`,
    ``,
    `version: "1.0.0"`,
    `conflict_resolution: "deny_overrides"`,
    ``,
    `policy_files:`,
  ];
  for (const category of GOVERNANCE_CATEGORIES) {
    indexLines.push(`  - "${category}.yaml"`);
  }
  files.push({
    path: '.vibe/policies/index.yaml',
    content: indexLines.join('\n'),
  });

  return files;
}
